name: build-time-project


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
    
      - uses: AutoModality/action-clean@v1   
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
#       - name: Stop container
#         run:  |
#           docker container stop nodejs-image-demo
          
#       - name: Remove container
#         run:  |
#           docker container rm nodejs-image-demo
          
#       - name: Remove an image
#         run:  |
#           docker rmi testdemo12/nodejs_image-demo
          
      - name: Build an image
        run: |
          docker build -t testdemo12/nodejs_image-demo .
      
      
      - name: Run the container
        run: |
          docker run --name nodejs-image-demo -p 8007:8080 -d testdemo12/nodejs_image-demo
